language: android
jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/

env:
  global:
    MALLOC_ARENA_MAX=2
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - build-tools-23.0.0
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_script:
    - export "JAVA_OPTS=-Xmx1024m"
    - export "JAVA7_HOME=/usr/lib/jvm/java-7-oracle"
    - export "JAVA8_HOME=/usr/lib/jvm/java-8-oracle"

script:
    - ./gradlew :app:test :app:jacocoUnitTestReport :app:coveralls --stacktrace